# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bf1e0d0b-5328-423b-9541-d435f944a246";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bf1e0d0b-5328-423b-9541-d435f944a246".device = "/dev/disk/by-uuid/bf1e0d0b-5328-423b-9541-d435f944a246";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/52D2-FE24";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-71d6ae04-c85d-405a-8bf9-65a25c2ae02b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
